### PR TITLE
add dockerfile and makefile

### PR DESCRIPTION
**Pull request by avcuenes**

### CODE REVIEW

**Comment by avcuenes** [comment]
@SamuraiChamploo Can you check?

**Comment by SamuraiChamploo** [comment]
> @SamuraiChamploo Can you check?

Can you add a description of the new files, because I don't often use docker and Makefiles to compile my projects

**Comment by avcuenes** [comment]
I added information to READme.

**Comment by SamuraiChamploo** [comment]
> I added information to READme.

thanks for your contribution

**Pull request merged**
